name: GLSL Validator

on:
  push:
    branches: [ master ]
    paths: [ '**.frag' ]
  pull_request:
    branches: [ master ]
    paths: [ '**.frag' ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  ubuntu2004:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt update && sudo apt install -y glslang-tools

    - name: Validate Shaders
      run: glslangValidator src/shaders_110/shapecorners.frag src/shaders_140/shapecorners.frag
